Add entityFilter for filter complexity objects
AKoulabukhov/Percy pull request #3
Opened 2019-06-21 16:04 UTC by SpectralDragon

2019-06-21 16:04 UTC, SpectralDragon commented on Percy/Classes/Percy+LiveList.swift
> +    private func tryEvaluateFilters(entity: T, object: NSManagedObject) -> Bool? {
Тут приходится смотреть на два фильтра сразу, поэтому завел этот метод

2019-06-21 16:05 UTC, SpectralDragon commented on Percy/Classes/Percy+LiveList.swift
> +            return nil
А вот тут, нужно учитывать, что фильтров нету, поэтому делаем что-то иное. Раньше было `if let filter = self.filter`

2019-06-24 08:06 UTC, AKoulabukhov commented on Percy/Classes/Percy+LiveList.swift
> +    public func makeLiveList<T>(predicate: NSPredicate? = nil, sorting: LiveList<T>.Sorting? = nil, filter: LiveList<T>.EntityFilter? = nil) -> LiveList<T> {
Почему здесь по какой-то причине поменялся нейминг, а в самом класс листа нет?
Либо сделай там predicate и filter, либо тут (object/entity)filter

2019-06-24 08:08 UTC, AKoulabukhov commented on Percy/Classes/Percy+LiveList.swift
> +        let filtredItems = entityFilter.flatMap { items.filter($0) } ?? items
filtEred

2019-06-24 08:11 UTC, AKoulabukhov commented on Percy/Classes/Percy+LiveList.swift
> +        guard let currentObjectIndex = items.firstIndex(where: { $0.id == entity.id }) else { return }
Сломает функциональность. Простой кейс - был удаленный объект isDeleted = true, у себя в приложении выводишь НЕудаленные. Объект восстановили, isDeleted = false. Но он не появится в твоем списке, потому что его там не было.

2019-06-24 08:16 UTC, AKoulabukhov commented on Percy/Classes/Percy+LiveList.swift
> +            return objectFilter.evaluate(with: object) && entityFilter(entity)
Сейчас кажется, что это не супер. Возможно надо еще подумать над тем как организовать доп. фильтрацию. Между двумя фильтрами строго &&, а если надо || (например, kindId = UserProfiles (predicate) || password.service.category == .other), фильтрация предикатом заведомо быстрее, потому могу представить кейс, где будет ||.

2019-06-24 08:23 UTC, AKoulabukhov commented on Percy/Classes/Percy+LiveList.swift
> +            return nil
Будет работать быстрее и выглядеть проще, если просто сделать:
if let objectFilter = objectFilter, !objectFilter.evaluate(with: object) { return false }
if let entityFilter = entityFilter, !entityFilter(entity) { return false }
return true

Однако в виду предыдущего комента про связывание фильтров логическим оператором (&& ||) коммент, скорее всего, не имеет смысла

2019-06-24 08:26 UTC, AKoulabukhov requested changes
Предлагаю подумать над тем как сделать фильтры с возможностью не хардкодить оператор их объединения.

2019-06-24 10:05 UTC, SpectralDragon commented on Percy/Classes/Percy+LiveList.swift
> +    public func makeLiveList<T>(predicate: NSPredicate? = nil, sorting: LiveList<T>.Sorting? = nil, filter: LiveList<T>.EntityFilter? = nil) -> LiveList<T> {
Исправил.

2019-06-24 10:06 UTC, SpectralDragon commented on Percy/Classes/Percy+LiveList.swift
> +        let filtredItems = entityFilter.flatMap { items.filter($0) } ?? items
Исправил

2019-06-24 10:09 UTC, SpectralDragon commented on Percy/Classes/Percy+LiveList.swift
> +        guard let currentObjectIndex = items.firstIndex(where: { $0.id == entity.id }) else { return }
Да, уже испытал на своей ветке эту ошибку, при этом же кейсе, который ты описал)

2019-06-27 16:19 UTC, closed without merging